FROM debian:bookworm

LABEL maintainer="Ihor Olkhovskyi <ihor@provoip.org>"

RUN apt-get update \
    && apt-get install -y \
        libglib2.0-dev \
        pkg-config \
        zlib1g-dev \
        libjansson-dev \
        libmicrohttpd-dev \
        libconfig-dev \
        libnice-dev \
        libssl-dev \
        libsrtp2-dev \
        libwebsockets-dev \
        libogg-dev \
        libcurl4-openssl-dev \
        cmake \
        git \
        curl \
        wget \
        dh-autoreconf \
    && cd /opt \
    && git clone https://github.com/meetecho/janus-gateway.git \
    && cd janus-gateway \
    && sh autogen.sh \
    && ./configure --prefix=/opt/janus \
        --disable-plugin-audiobridge \
        --disable-plugin-lua \
        --disable-plugin-duktape \
        --disable-plugin-textroom \
        --disable-plugin-nosip \
        --disable-plugin-sip \
    && make \
    && make install \
    && mkdir -p /opt/janus/etc/janus

ENTRYPOINT [ "/opt/janus/bin/janus" ]
